-- Adminer 4.8.1 MySQL 10.5.15-MariaDB-1:10.5.15+maria~focal dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `verzie`;
CREATE TABLE `verzie` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '[A]Index',
  `id_user_main` int(11) NOT NULL DEFAULT 1 COMMENT 'Id užívateľa',
  `cislo` varchar(10) COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Číslo verzie',
  `subory` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT 'Zmenené súbory',
  `text` text COLLATE utf8_bin DEFAULT NULL COMMENT 'Popis zmien',
  `modified` timestamp /* mariadb-5.3 */ NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'Dátum a čas zmeny',
  PRIMARY KEY (`id`),
  UNIQUE KEY `cislo` (`cislo`),
  KEY `datum` (`modified`),
  KEY `id_clena` (`id_user_main`),
  CONSTRAINT `verzie_ibfk_1` FOREIGN KEY (`id_user_main`) REFERENCES `user_main` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='Verzie webu';

INSERT INTO `verzie` (`id`, `id_user_main`, `cislo`, `subory`, `text`, `modified`) VALUES
(1,	1,	'0.1.0',	NULL,	'Východzia verzia',	'2017-09-07 12:43:25'),
(2,	1,	'0.1.1',	'Texy',	'- Implementácia texy a texyly\n- Oprava nájdených chýb',	'2017-10-10 09:52:04'),
(3,	1,	'0.1.3',	'Prílohy, slider',	'Testovacia verzia, v ktorej bolo opravené:\n\n- **Administrácia - Prílohy článkov:** možnosť pridať súčasne viac príloh, inline editácia popisu a názvu prílohy.\n- **Administrácia - Slider:** pridaná možnosť upravovať zobrazenie jednotlivých položiek.\n- **Administrácia:** náhrada ckeditora za texylu.\n- **Web - Slider:** zobrazovanie obrázku podľa príslušnej časti.\n- **Web - Lightbox:** upgrade na verziu 0.5.6 a pridanie popisu k obrázkom.',	'2017-10-10 09:51:40'),
(4,	1,	'0.1.4',	'Merge pull request #2 from petak23/nittro',	'Testovacia verzia v ktorej bolo zmenené:\n- Aplikácia \"nittra\":https://www.nittro.org/ .\n- Úprava požitia lightbox-u.\n- Úprava administračnej časti evidencie verzií.\n- Rozdelenie konfigurácie pre jednotlivé moduly.\n- Úprava adresárovej štruktúry.\n- Aktualizácia vzhľadu.\n- Aktualizácia vzhľadu príloh.\n- Pridanie možnosti pridania náhľadového obrázka pre neobrázkové prílohy.\n- Úprava sekcie zoznamu albumov podľa JP.\n',	'2017-11-15 10:47:16'),
(5,	1,	'0.1.5',	'rôzne',	'Prispôsobenie vzhľadu úrovne 3',	'2017-12-27 11:59:49'),
(6,	1,	'0.1.6',	'úroveň 3 a 4',	'- Prispôsobenie vzhľadu úrovne 3. a 4..\n- Aktualizácia nittra a lightbox-u.\n- Odstránenie koncovky z názvu prílohy.\n- Práca na admin časti pre rámčeky - pridaná časť pre fotoalbum zmeny rámčekov obrázkových príloh v úrovni 4. pre každú časť zvlášť.\n- Prispôsobenie 4. úrovne pre prehliadanie obrázkov s rámčekmi.',	'2017-12-27 12:04:06'),
(7,	1,	'0.1.7',	'mnohé',	'- Zmena názvov stĺpcov(spec_nazov=web_name, subor=main_file, thumb=thumb_file, zmena=change) tabuľky dokumenty a s tým súvisiace zmeny. \n- Pridané zobrazenie videa pre front modul.\n- Pridaná časť produktov aj pre front časť. \n- Zmena názvov stĺpcov(nazov=name, popis=description) tabuľky dokumenty a s tým súvisiace zmeny.\n- Pridaná časť produktov pre admin časť. Nedokončené. Update fontawesome na verziu 5.0.2 na admin strane.',	'2018-01-16 09:15:17'),
(8,	1,	'0.2.1',	'Issue #4, #5, #6',	'Sumár:\n======\n**Zmena načítania produktov.**\n\n**V administrácii: oprava ikoniek; pre slider: pridanie kompletného stromu menu do formulára - položka: *Zobrazenie pre*;** \n\nDetaily:\n======\nFrontend\n----------\n- Úrava pre IE.\n- Načítanie produktov ajaxovo.\n- Oprava chyby pri zobrazení príloh alebo produktov.\n\nAdministrácia\n-------------\n- Oprava ikoniek v administrácii a odstránenie nepotrebných. \n- Presun nastavení produktov do samostatnej časti. Issue \"#5\":https://github.com/petak23/bwfoto/issues/5\n- V údajoch pridaná možnosť zobraziť alebo skryť separátne nastavenia.\n- Slider: Odstránenie väzby súborov na adresáre a presun ich nastavení do configu.\n- Slider: Pridanie kompletného stromu menu do formulára - položka: *Zobrazenie pre*.\n- Slider: zmena názvu ikoniek.\n- Presun nastavenia okrajového rámčeka na kartu produktov Issues \"#4\":https://github.com/petak23/bwfoto/issues/4\n- Odstránenie chyby v mazaní príloh\n\nOstatné\n-------\n- Oprava zobrazovania textu(texi) v emailoch. Issue \"#6\":https://github.com/petak23/bwfoto/issues/6\n- Odstránenie zmetočných adresárov v prílohách článkov a produktov. \n- Zmazanie nepotrebných častí.\n- Presun index.php do adresára www a s tým spojené zmeny.\n- Update fontawesome na verziu 5.2.0; \n- Update bootstrap na verziu 4.1.2; \n- Update adminer na verziu 4.3.6. \n- Použitie npm správcu. \n- Odstránenie zbytočných css a js.\n',	'2018-08-30 08:35:32'),
(9,	1,	'0.3.0-alfa',	'Upgrade to v 0.3.0',	'- **Oprava chyby: zobrazenie prvého obrázku alebo produktu pri prvom zobrazení článku.**\n- Upgrade nette na verziu 2.4\n- Aplikácia zmien z echo-msz.eu ale s prispôsobením komponent na verziu PHP 7.0.33\n- Inovácia vzhľadu v administrácii, zatiaľ ešte nie úplne dokončená \"(AdminModule) .{color: gray}\".\n- Aktualizácia komponent vzhľadu v package.json \"(fontawesome: 5.2.0, bootstrap: 4.4.1, jquery: 3.4.1, naja: 1.5.1, nette-forms: 2.4.2, popper.js: 1.16.1) .{color: gray}\". \n- Aktualizácia správcu databázy \"(adminer v 4.7.6) .{color: gray}\". \n- Oprava chyby v menu FrontModule a upgrade pre novú verziu Texy.',	'2020-05-04 11:55:19'),
(10,	1,	'0.3.0-beta',	'Rôzne; jquery 3.5.0',	'- Oprava drobných chýb v prihlásení.\n- Oprava chyby v slideri(issue \"#12\":https://github.com/petak23/bwfoto/issues/12). Rebase model/Table.php.\n- Rebase model/Dokumenty.php; model/Products.php a model/UserManager.php.\n- Oprava chyby v pridávaní podčlánku v adninistrácii.\n- Refaktoring fotogalérie na frontende.\n- Oprava zobrazenia produktov v AdminModule. \n- Update jquery na 3.5.0.\n- Oprava zobrazenia príloh vo FrontModule a premenovanie adresára presenters na Presenters.\n- Oprava issue \"#11\":https://github.com/petak23/bwfoto/issues/11 - A13 - V administracii pri zozname príloh( miniatúry fotografií) keď kliknem na foto aby sa mi zobrazila fotka tak sa zobrazí na ľavej strane - nie je vycentrovaná na stred',	'2020-05-04 12:02:51'),
(11,	1,	'0.4.0-RC',	'Nette 3.0, adminer 4.7.7',	'- Oprava issue \"#10\":https://github.com/petak23/bwfoto/issues/10 - A10 - nekorektné zobrazenie úrovne 3. a 4.\n- Oprava zobrazenia formulárov na karte Produktu pre AdminModul a odstránenie chyby zobrazenia nastavenia okrajov. \n- Odstránenie chyby zobrazenia hlavného menu v AdminModul-e.\n- Úpravy potrebné pre prechod na nette 3.0,\n- odstránenie drobných chýb,\n- vypustenie webloader-a\n',	'2020-05-26 13:53:54'),
(12,	1,	'0.5.0',	'Vzhľad, Oprava chýb A9 a A7',	'- Prvá časť zmeny vzhľadu: *Titulka, Prihlasovacia stránka*.\n- Oprava chyby \"#16\":https://github.com/petak23/bwfoto/issues/16 - **A9 - max. počet súčasne nahrávaných súborov**.\n- Oprava chyby \"#15\":https://github.com/petak23/bwfoto/issues/15 - **A7 - doplň priebeh uploadu - pre produkty**.\n- Doplnená možnosť nastavenia max. počtu naraz nahrávaných súborov v rozsahu 5 ... 150.\n- Integrácia prvej verzie komponenty pre vyhľadávanie na stránke.\n- Integrácia jQuery-FileUpload pre nahrávanie súborov.',	'2020-07-30 09:21:42'),
(13,	1,	'0.5.3',	'Webpack, a iné',	'- Pridanie \"webpack-u\":https://webpack.js.org/\n- Refaktoring časti editácie údajov webu.\n- Adminer presunutý na composer-a.\n- Update na \"nette 3\":https://nette.org/cs/maintenance',	'2020-11-12 19:30:00'),
(14,	1,	'0.5.3b',	'update na php 7.4',	'- Oprava drobných chýb\n- Update na php 7.4\n- Update npm',	'2020-12-29 14:28:48'),
(15,	1,	'0.5.4a',	'Vue fotogaléria',	'- Vyriešenie chyby \"#14\":https://github.com/petak23/bwfoto/issues/14 - vytvorenie úrovne č.5 a preklopenie fotogalérie do \"vue.js\":https://vuejs.org/ - chýba už len grafický design.\n- Presun nastaveni \"webpack\":https://webpack.js.org/ vývojového servera do config.local.neon a doplnenie nastavení \"webpack-u\":https://webpack.js.org/.\n- Prispôsobenie \"webpack-u\":https://webpack.js.org/ pre vue komponenty.\n- Presun modulov css a js do app/assets.\n\n',	'2021-01-11 13:58:52'),
(16,	1,	'0.5.5e',	'Oprava chýb, úprava vzhľadu a fotogalérie',	'Urobené:\n========\n- **Počas nahrávania fotogalérie sa zobrazí animovaný spinner** - \"aktualizované 08.03.2021 .{color: red}\"\n- odstránenie kontroly na velkosť obrázka pre \"slider\" - obrázok v hlavičke - \"aktualizované 27.02.2021 .{color: purple}\"\n- oprava zobrazenia - \"aktualizované 27.02.2021 .{color: purple}\"\n- zmena vzhľadu úrovne č. 4 a 5. V úrovni č. 4 je použitý tretinový spôsob. - \"aktualizované 27.02.2021 .{color: purple}\"\n- oprava chýb\n- rozchodenie js v administrácii\n- oprava chyby zobrazenia\n- skrytie názvov miniatúr vo fotogalérii.\n\nNie je urobené:\n===============\n- v prípade zobrazenia na obrazovke so šírkou menšou ako 576px sa nezobrazuje úroveň č. 4 a 5.\n- dokončiť vzhľad pre úrovne č. 4 a 5.',	'2021-03-08 17:18:08'),
(17,	1,	'0.6.2',	'Vue fotogaléria',	'\"releas - 0.6.2\":https://github.com/petak23/bwfoto/releases/tag/0.6.2\n---------------------------------------------------------------------\n\n- Úprava fotogalérie aj pre malé displeje. Pridanie ovládania klávesnicou.\n- Počas nahrávania fotogalérie sa zobrazí animovaný spinner.\n- Oprava vzhľadu, odstránenie kontroly rozmerov obrázka slideru.\n- Skrytie názvov miniatúr vo fotogalérii.\n\n',	'2021-03-20 06:38:08'),
(18,	1,	'0.6.4',	'rôzne',	'- Opravené chyby v MapaModule\n- Opravená chyba v prílohách v AdminModule',	'2021-04-26 05:57:39'),
(19,	1,	'0.7.0',	'autocomplete',	'- Rozšírené možnosti vyhľadávania na názvy článkov, text v článkoch, názvy a popis dokumentov a názvy a popis produktov.\n- Opravy zistených chýb\n- Oprava radenia príloh vo FrontModule. \n- Pridaná možnosť zobraziť na začiatku konkrétny obrázok vo fotogalérii podľa id.',	'2021-05-03 09:33:31'),
(20,	1,	'0.8.03',	'php 8.0; rôzne',	'- Refaktoring;\n- Prechod na PHP 8.0; \n- Oprava editácie nadpisov; \n- Presun nastavenia okrajov do hlavného nastavenia článku; \n- Začiatok práce na lazyloading-u miniatúr obrázkov. \n- Oprava chýb v administrácii pri mazaní titulného obrázka.\n- Oprava odkazu na pdf.\n- Iné drobné opravy.',	'2021-11-16 13:31:28'),
(21,	1,	'0.8.06',	'Grafické zmeny',	'- zmenšená fotka v slideri - úroveň 2 - výška 220px\n- zmenený obrázok loga pridaná žiara\"* - zmena cesty (názov súboru, editované v layout.latte)* .{color: gray}\"\n- odstránené pozadie loga\"* - nav .navbar-brand (bwfoto.css)* .{color: gray}\"\n- obsah posunutý vyššie\"* - znížený margin-top pre webcontent (x_docasne.css)* .{color: gray}\"\n- zmena veľkosti písma podľa šírky okna \"*- pridané pravidlo :root do (bwfoto.css)* .{color: gray}\"\n- pridaná zmena šírky obsahu podľa šírky okna \"*- kontajner .frame - zmena pridaná do media queries (bwfoto.css)* .{color: gray}\"\n- vystredené náhľady kategórií pri úzkej obr. \"*- pridané pravidlo webParts .row (bwfoto.css)* .{color: gray}\"\n- horné menu posunuté vyššie väčšia priehľadnosť pozadia zmenšený font \"*- pridané pravidlá nav .nav-item .nav-link, #topNav, #navbarSupportedContent (všetko v bwfoto.css)* .{color: gray}\"\n- upravená pozícia šípok v úrovni 4 \"*- pridané vlastnosti v .lightbox-img .modal-body (vue_fotogalery.css)* .{color: gray}\"\n- \"*oprava package.json a webpack.config.json* .{color: gray}\"',	'2021-11-16 13:31:20'),
(22,	1,	'0.8.18',	'Opravy',	'\"**Aktualizované 02.12.2021:** .{color: red}\"\n- \"rozdelenie UserLangMenu na dve samostatné komponenty .{color: gray}\"\n- \"opravy chýb pre viacjazyčnosť webu .{color: gray}\"\n\n-------------------\n**Staršie:**\n\n- oprava rozsahu súčasného pridania produktov na 5 ... 500,\n- oprava, doplnenie popisu a vložená kontrola odkazov na položky hl. menu v editácii slideru,\n- oprava ukladania textov článku.\n- oprava lazy-loadingu obrázkov,\n- pridanie šablony pre panorámy,\n- oprava chyby pri mazaní článku,\n- oprava chyby pri mazaní príloh,\n- \"úprava, rozdelenie HomepagePresenter, .{color: gray}\" \n- \"pridaný API modul pre užívateľa, .{color: gray}\"\n- \"update composer a npm. .{color: gray}\"',	'2021-12-02 12:08:47'),
(23,	1,	'0.8.20',	'Opravy',	'- Oprava chyby \"#34\":https://github.com/petak23/bwfoto/issues/34 - Zmazanie telef. kontaktu na titulke.\n- Oprava chyby \"#35\":https://github.com/petak23/bwfoto/issues/35 - Zmazanie položky menu.\n- Oprava chyby \"#36\":https://github.com/petak23/bwfoto/issues/36 - Homepage dole - nadpis.\n- Oprava chyby \"#37\":https://github.com/petak23/bwfoto/issues/37 - Administrácia zmenšenie náhľadov.\n- Do hornej lišty v administrácii pridaný odkaz na aktuálne zobrazený článok. Odkaz je viditeľný len v prípade, ak takýto odkaz existuje. \n- V hornej lište v administrácii zmena nadpisu \"Administrácia\" na informáciu o aktuálne prihlásenom užívateľovi.\n- Oravy drobných chýb.',	'2022-01-07 13:07:17'),
(24,	1,	'0.8.23',	'Zmeny vzhľadu',	'- odstránene pozadie v zmenšenom menu \"- trieda shrink v bwfoto.css .{color: gray}\"\n- skrytie horného menu po rolovani; namiesto zmenšenia sa horné položky menu a vyhľadávacie pole skryjú \"- pridana trieda hidecont v bwfoto.css a upraveny navshrink.js .{color: gray}\" POZNAMKA: nevedel som spravit to aby sa tlacidlo hamburger zobrazovalo ked sa skryju polozky horneho menu.  - \"Vyriešené .{color: green}\"\n- zobrazovanie iba troch nahladov v kat. 2 cize nahlady albumov. 4 vedla seba sa zobrazia az od velkosti xxl \"- upraveny subor BWfoto_foto_section.latte .{color: gray}\"\n- upravena medzera medzi popisom a nadpisom albumu, odsadeny cely album tak aby bol nadpis (ktory je pod obrazkom blizsie k tomu nahladu kde patri) \"- v bwfoto.css upravene: #webAlbums .album, #webAlbums h3, footer .{color: gray}\"\n- upravene nahlady na titulnej strane, uroven 1 - nahlady pri zmene sirky neboli rovnake (Juraj vie :)) \"- zmene viacere pravidla v bwfoto.css nama v pravidlach #webParts-md a webParts. Zmenena aj sablona BWfoto_fixed_homepage.latte .{color: gray}\"\n- velky nahlad v urovni 3 posunuty vo svojom priestore na stred aby nebol tak velmi vzdialeny od malych nahladov \"- upravene v sablone Fotogalery.vue .{color: gray}\"\n- opraveny problem so sipkou v urovni 4 na mensich zobrazeniach \"- upravy vo vue-fotogallery.css niekde v pravidlach lightbox-img a tiez uprava vo Fotogalery.vue .{color: gray}\"\n',	'2022-01-17 07:53:44'),
(25,	1,	'0.8.27',	'Foto koláž',	'\"**Aktualizované 17.2.2022:** .{color: red}\"\n- Do foto koláže pokusne pridané 3 rôzne schémy podľa šírky okna (zlomy pri 320, 700px).\n- Možnosť rozšíriť počet schém a body zlomu.\n\n---\n\n- Pokusne pridaná fotokoláž do článku: \"Časť A-2\":http://test.bwfoto.sk/clanky/cast-a-2 . Zmena výšky riadku.\n\n- Oprava chýb v časti užívateľov.',	'2022-02-17 14:06:40'),
(26,	1,	'0.8.29',	'Foto koláž',	'Úprava koláže. Pridaná možnosť mať 1 fotku v riadku inej šírky ako ostatné podľa nasledujúcej schémy:\n/--code js\nsch: [\n        { // 1. schéma pre šírku koláže do 320px\n\n          // Max. šírka koláže pre ktorú platí\n          max_width: 320,  \n\n          // Minimálny počet fotiek na riadok\n          min_row: 1,      \n\n          // Počet fotiek v jednotlivých riadkoch + min_row\n          schema: [1, 0, 2, 1, 2, 0, 1, 2], \n\n          // Výška jednotlivých riadkov\n          height: [\"110px\", \"150px\", \"78px\", \"110px\", \"78px\", \"150px\", \"110px\", \"78px\"],\n\n          // Poradie fotky v riadku, ktorá má byť širšia ako ostatné v riadku:\n          // Ak je zadané číslo väčšie ako 0 (1,2,...) tak tá konkrétna bude širšia, \n          // ak je zadané 0 generuje sa náhodne,\n          // ak je zadané -1 všetky fotky v riadku budú rovnaké.\n          widerPhotoId: [1, 0, 1, 0, 2, 0, 1, 2],\n        },\n        { // 2. schéma pre šírku koláže od 321px do 700 px\n          max_width: 700,\n          min_row: 2,\n          schema: [1, 0, 1, 2, 1, 0, 2, 1],\n          height: [\"170px\", \"235px\", \"170px\", \"120px\", \"170px\", \"235px\", \"120px\", \"170px\"],\n          widerPhotoId: [1, 0, 1, 0, 2, 0, 1, 2],\n        },\n        { // 3. schéma pre šírku koláže od 701px do 1300 px\n          max_width: 1300,\n          min_row: 3,\n          schema: [0, 1, 2, 3, 0, 1],\n          height: [\"300px\", \"220px\", \"180px\", \"170px\", \"235px\", \"220px\"],\n          widerPhotoId: [1, 0, -1, 0, 2, 0],\n        },\n        { // 4. schéma pre šírku koláže od 1301px do 100000 px\n          max_width: 100000,\n          min_row: 3,\n          schema: [0, 1, 2, 3, 1, 0],\n          height: [\"400px\", \"300px\", \"265px\", \"220px\", \"300px\", \"400px\"],\n          widerPhotoId: [1, 0, -1, 0, 2, 0],\n        },\n      ],\n\\--',	'2022-02-22 12:45:32'),
(27,	1,	'0.8.33',	'články',	'- Oprava chyby v zobrazení článku.\n- Refaktoring časti článkov na front module.\n- Odstránenie nepotrebnej DB tabuľky: clanok_lang.',	'2022-02-28 16:26:45'),
(28,	1,	'0.8.37',	'Panorámy',	'\"Aktualizované: 13.03.2022: .{color: red}\"\n- Zjednodušená konfigurácia fotokoláže.\n- Odstránené chyby v panorámach a fotokoláži.\n- Oprava ukladania užívateľských dát na FrontModule.\n\n-------------------\n\n\n- Aktualizovaná časť fotopanorám. \n- Aktualizovaná časť pridávania produktov. Miniatúry produktov sa vytvárajú podľa toho, či je nastavená ako šablóna článku panoráma alebo nie. \n- Nahrané nové nastavenie pre fotokoláž.',	'2022-03-12 20:42:31'),
(29,	1,	'0.9.03',	'Editácia na front module',	'Nová funkcionalita\n------------------\n\n- Editácia nadpisu článku: Pridaná možnosť editovať nadpisy článkov priamo z FrontModulu\n- Zmena poradia položiek:  Pridaná možnosť zmeniť poradie položiek na FrontModule.',	'2022-04-04 12:20:29'),
(30,	1,	'0.9.05',	'Oprava chýb',	'- Oprava chýb vo fotokoláži (zmena výšky riadku) a zlé proporcie obrázku po kliknutí naň.\n- Zjednodušenie konfigurácie fotokoláže.\n- Oprava chybného zobrazenia editácie na titiulke.\n- Oprava podtitulky\n- Oprava chybných ikoniek v administrácii.',	'2022-04-04 12:20:29'),
(31,	1,	'0.9.11',	'texyla, fontawesome 6, slider,',	'\"**Aktualizácia 6.4.2022:** .{color: orange}\"\n- Do fotogalérie pridaná možnosť posúvať fotky v 4. kat. prstom pohybom všetkými smermi.\n\n-------------------\n\n- Opravy zobrazenia slider-u. Doplnené pomocné informácie.\n- Začaté práce na editácii textov pre vue.js priamo na front module. Ikonka vedľa editácie nadpisov. \"Táto funkcionalita je v štádiu experimentovania, takže nie všetko je funkčné. .{color: orange}\"\n- \"V js a vue súboroch nahradenie definovania premennej var za let .{color: gray}\"\n- Aktualizovaný fontawesome na verziu 6.\n- Oprava zistených chýb.',	'2022-04-06 08:38:48'),
(32,	1,	'0.9.19',	'Uploadery, chyby',	'\"Aktualizované 03.05.2022: .{color: orange}\"\n- Pridanie odkazu z článku na front-e priamo do administrácie.\n\n-------------------\n\n- Práce na vue single uploadery.\n- Práce na multi uploadery a upratovanie okolo.\n- Výmena funkcie strftime za date.\n- Oprava zadávania dátumu pri platnosti článku.\n- Presun komponenty pre zmenu okrajového rámčeka do vue.\n- Odstránenie chyby: User Deprecated Filter |noescape should be placed at the very end.\n- Odstránenie chýb.',	'2022-05-03 13:38:50'),
(33,	1,	'0.9.30',	'mnoho',	'- Vypustenie Ublaboo datagridu a nahradenie Vue komponentov.\n- Oprava vzhľadu na titulnej stránke.\n- Oprava drobných chýb.',	'2022-06-16 12:46:38'),
(34,	1,	'0.9.35',	'Príloha a produkty',	'- Doplnenie tabuľky produktov a príloh o označovací stĺpec a možnosť mazania viacerích položiek naraz.',	'2022-06-28 10:53:46'),
(35,	1,	'0.9.37',	'npm, composer',	'- update npm \n- update composer\n- update Readme.md',	'2022-11-09 14:12:14');
